name: Android CI/CD

on:
  push:
    branches:
      - '**'  # Triggers on pushes to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin' # Specify the JDK distribution
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'  # Specify the Ruby version
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependencies
        run: npm install
      - name: Install Ruby Gems
        run: bundle install  # Install dependencies from Gemfile, including Fastlane
      - name: Run Tests
        run: bundle exec fastlane test
      - name: Beta Release
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bundle exec fastlane beta
