name: Android CI/CD

on:
  push:
    branches:
      - '**'  # Triggers on pushes to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - name: Install Bundler
        run: gem install bundler
      - name: Install Ruby Gems
        run: |
          bundle config set path 'vendor/bundle'  # Set the bundle path
          bundle install  # Install dependencies from Gemfile
      - name: Install Fastlane
        run: gem install fastlane -NV  # Directly install Fastlane with gem install
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: |
          cd android  # Change to the android directory
          export BUNDLE_GEMFILE=./Gemfile  # Ensure the correct Gemfile is used
          export BUNDLE_PATH=./vendor/bundle  # Use the local bundle path
          bundle exec fastlane test
      - name: Beta Release
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd android  # Change to the android directory
          export BUNDLE_GEMFILE=./Gemfile  # Ensure the correct Gemfile is used
          export BUNDLE_PATH=./vendor/bundle  # Use the local bundle path
          bundle exec fastlane beta
